.travis.yml, README.md, composer.json, src/Attachment.php, src/Parser.php, test/ExceptionTest.php, test/ParserTest.php
Now that 5.3 is EOL (2014-08-14) it is no longer receiving security updates and everyone should be encouraged to use a more up to date and secure version
=> Remove PHP 5.3 support

README.md, composer.json, phpunit.xml, src/Attachment.php, src/Charset.php, src/Contracts/CharsetManager.php, src/Exception.php, src/Parser.php, test/ExceptionTest.php, test/ParserTest.php
Now that the project is under it's own namespace on github, shouldn't it be under the same namespace on packagist and in the code?
If accepted, this pr would require a version bump to 2.0 so maybe we could bundle in some other improvements too? And if support for 5.3 is dropped we could use some of the features introduced in 5.4
=> Update the namespace to be consistent

src/Parser.php, tests/ExceptionTest.php, tests/ParserTest.php
(+ splitted decodeHeader so it doesn’t remove multi-value headers)
In a project I needed the ability to fetch all headers. Let me know what you think of this.
Best,
Nicolas
=> Added method getHeaders

src/Parser.php
Improve parameter type-hinting (PHPStorm was considering `File` as PHP own `File` class
=> Improve parameters type hinting

src/Parser.php
When the subject of an e-mail cannot be decoded by iconv(), the getHeader('subject') call generates iconv() warnings. It makes it impossible to retrieve the header contents (even without decoding). I added a getRawHeader() to make it possible to access raw headers.
Sample invalid subject (consists of two parts, but decodeHeader() currently doesn't handle that):
````=?GB2312?B?1rvSqsTjxNzP66Os1rvSqsTjz+vX9qOsv827p7K7ysfOyszio6zLq8+yyO28?= =?GB2312?B?/rDvxPq94r72o6GjoQ==?=````
=> Add getRawHeader() method to allow retrieving headers without charset conversion

src/Parser.php
if CID is generated like image-34-*, replacement will cause a problem
image-34-1
image-34-2
...
image-34-10
image-34-11
src for image-34-10 will be: {data}0
=> Correct CID replacement

src/Attachment.php
This function will help with some downstream attachment processing so we do not have to save each attachment to a temp file over and over.
=> Added a function to use the attachent stream

README.md
I meant to get to this sooner, but I hope it's still useful. Please review that everything I've written is correct, because I had to make some guesses about what you meant. Especially the "Why" section (which is the most important section to get right!).
=> Copy editing suggestions in README

src/Parser.php, tests/ParserTest.php
At the moment, case folding is applied to header names rendering them exclusively in lower-case. This change updates the Parser->getRawHeader($name) function and related functions to always fold the header name to lower-case.
This prevents confusion when someone tries to match the header name exactly as it's stored in an RFC(2)822 file and matches the functionality offered by a lot of other libraries that deal with headers.
NB: Adding a test for this would be trivial, however, I was not sure how to kick them off myself. That would be a nice future addition to README.md :-)
=> Make header retrieval case-insensitive

README.md, src/Parser.php, tests/ParserTest.php
Added an optional argument to getAttachments and saveAttachments to include inline attachments (defaults to false). Also update the README file accordingly.
=> Added option to include/exclude inline attachments

src/Parser.php, tests/ParserTest.php, tests/mails/issue133
=> Escape all potentially unsafe characters from attachements filenames.

src/Parser.php, tests/ExceptionTest.php, tests/ParserTest.php, tests/mails/m0026
This is an alternative solution to PR #63 where we now prevent filename collisions by default.
* Public API for ->saveAttachments() is expanded with a filename strategy argument
* Makes use of tempnam() to generate unique filenames whenever necessary
* Tests added to expose duplicate filename bug and test new filename strategy functionality
=> Fix handling of duplicate attachment filenames and offer strategies in ->saveAttachments()

src/Parser.php, tests/ParserTest.php, tests/mails/m0027
Added m0027 and changed testIlligalAttachementFilename() to use m0027. This issue  is related to #133
=> Fix for AttachementFilename when only content-name is used

src/Parser.php, tests/ParserTest.php, tests/mails/issue158a, tests/mails/issue158b, tests/mails/issue158c, tests/mails/issue158d
This is PR #159 with the whitespace build fixes rebased into a single commit.
=> Fixes #158 : to not include parts from attachments in getMessageBody()

src/Parser.php, tests/ParserTest.php, tests/mails/m0028
The `partIdIsChildOfPart` check does not work in some cases.
The function `partIdIsChildOfPart` will return an incorrect result when:
- an email contains a multipart section with 10 or more child parts
- and one of these parts is the text or html content of the email
This is due to the fact that only the start of the string is compared. When for example `1.1` is compared to `1.10` this results in `true`.  If we append a period to the supposed parent part id we make sure that this can not happen and it does not break anything. 
In the new situation the `$parentPartId` will be changed to `1.1.`. This will match `1.1.1` but not `1.10`, which is the desired result.
=> Fix partIdIsChildOfPart check

src/Attachment.php, tests/AttachmentTest.php, tests/ParserTest.php
Instead of giving an attachment a unique filename and extension 'tmp'
when the original fileName already exists, the attachment is now saved
as the original fileName with a integer suffix and original extension.
When the suffix reaches the number 1000 and the fileName still already
exist, the fileName will be random and unique, but the extension still
remains the original one.
=> Save Attachment Enhancement.

src/Parser.php
Reference to my bug report on #250
I've updated the regex from `((^\.)|\/|(\.$))` to `((^\.)|\/|[\n|\r|\n\r]|(\.$))` (Extending it with `[\n|\r|\n\r]`). Test of the regex can be found here https://regex101.com/r/aEkWpt/2
To avoid missing one of the regex's next time I've centralized them within an `else` statement to not run it on non-matched filenames.
I've tested the code, please make sure you can reproduce the issue and that my PR fixes the issue.
Thanks.
=> Fix missing checks on escaping all potentially unsafe characters from the filename

composer.json, tests/AttachmentTest.php, tests/ExceptionTest.php, tests/ParserTest.php, tests/TestCase.php, tests/globals.php
[Support for PHPUnit 8 ends on February 7, 2020](https://phpunit.de/supported-versions.html), or in several days time.
=> Update composer.json to use PHPUnit 8 for testing

.github/workflows/main.yml
The package only depends on PHP and the extension, which are not installed with composer, therefore `--prefer-lowest` has no effect on them, and adds no value.
=> Do not test with lowest dependencies

.github/workflows/main.yml
It seems like a codecov token is [missing from settings](https://github.com/php-mime-mail-parser/php-mime-mail-parser/settings/secrets), and that's [what it says](https://github.com/php-mime-mail-parser/php-mime-mail-parser/runs/427745505#step:5:48). Coveralls is a different service, which means that a token for a different service might be a problem.
This PR changes to token to `CODECOV_REPO_TOKEN`, but I can't update it in the settings.
=> Update secret name for codecov.io

tests/ParserTest.php
=> Remove version check from testDecodeCharsetFailedIsIgnored

composer.json, phpunit.xml.dist, src/Attachment.php, tests/AttachmentTest.php, tests/ExceptionTest.php, tests/ParserTest.php, tests/TestCase.php, tests/globals.php
Fixed issues:
- Failing tests were not always cleaning up behind them, which required manual cleanup.
- `fopen` error handling test was failing on actual fopen errors because they're causing warnings.
- Mock variables weren't reset for failing tests, leading to more failures. 
Implementation notes:
- Luckily there weren't any hidden dependencies between tests. `executionOrder="random"` ensures there won't be any.
- `symfony/filesystem` greatly simplifies cleanup, and it's only a dev-dependency.
=> Simplify temporary directory handling and fopen()-related tests

src/Parser.php
It can never return an empty string as it is always called with a correct contentId.
I wish we could make this function private, or, even better, the entire class `final`.
=> Improve coverage for getEmbeddedData()

src/Parser.php
[Looking at the code of the extension](https://github.com/php/pecl-mail-mailparse/blob/9efc0652bd40c58556819a986e9cdbadc9ac5860/mailparse.c#L1452) it can be seen that there's always a charset.
=> Improve coverage for getPartCharset

src/Charset.php, src/Parser.php
Also simplify iso-2022-jp-ms substitution
=> decodeCharset does the aliasing, no need to do it twice

.github/workflows/main.yml, composer.json
I think we still don't get PR [coverage reports uploaded to codecov.io properly](https://codecov.io/gh/php-mime-mail-parser/php-mime-mail-parser/commits), and I'm not even sure this is possible, so at least we'll have this safeguard.
TBH I'm not a big fan of codecov.io, and I'd rather use something else like [Coveralls](https://coveralls.io/), but codecov kinda works and free, so it's better them rather than nothing else.
=> Enforce coverage level during CI

src/Attachment.php, src/Contracts/AttachmentInterface.php, tests/ParserTest.php, tests/mails/m0028, tests/mails/noAttachmentContentId
While working on a project, I executed the parser on all emails in https://github.com/mikel/mail/tree/master/spec/fixtures/emails,
It failed on a mail containing no ContentID for an attachment.
=> Ensure attachment contentId is a string

tests/ParserTest.php
- Using the `assertCount` to assert expected count is same as result count.
- Using the `assertIsArray` to assert expected type is `array`.
=> Improve assertions

README.md
Just makes it easier for people to go direct to the release they need instead of navigating the releases.
=> Added links to release tags for older versions

src/Parser.php
`Parser::getHeader()` only returns a string or boolean false, so narrowing the return to only specify false creates a minor DX improvement as analysis tools won't raise a warning if not checking for a boolean true return.
=> Narrow `Parser::getHeader()` return type

src/Parser.php
getRawHeader may return array, if the mail has multiple header lines, like a Received
=> Parser::getRawHeader() may returns array

src/MiddlewareStack.php, src/Parser.php
https://wiki.php.net/rfc/deprecate-implicitly-nullable-types deprecates implicit nullable parameter types in PHP 8.4
=> Fix deprecation warning in PHP 8.4
