README.md, composer.json
Removed imap dependency (Fixes #82)
=> remove imap dependency

README.md, src/Parser.php, tests/ExceptionTest.php, tests/ParserTest.php
Added a function to get the raw mail headers as a string. Useful for diagnostic purposes.
=> Added getHeadersRaw()

src/Parser.php, tests/ParserTest.php
=> Fixes #107 

src/Parser.php, tests/ParserTest.php
=> Ignore message body in getAttachments

.gitignore, src/Parser.php
=> [Parsing Streams] add more readable modes

src/Parser.php, tests/ParserTest.php
=> Fix attachment path

src/Charset.php, tests/ParserTest.php, tests/mails/issue212
=> Fix issue 212

src/Parser.php, tests/ParserTest.php, tests/mails/issue250
=> Fix missing checks on escaping all potentially unsafe characters from the filename

.github/workflows/main.yml, src/Charset.php, tests/ParserTest.php, tests/mails/failure.eml
=> Test issue 252

.github/workflows/main.yml
=> Update workflows to trigger on a PR

.github/workflows/main.yml, composer.json
=> Validate and normalize composer.json

tests/AttachmentTest.php, tests/ParserTest.php
According to my calculations with these four PRs the raw coverage should get to 100%.
=> Improve test coverage for Attachment

.github/workflows/main.yml, src/Attachment.php
- ~~Don't fail CI if coverage report fails to upload, just to save the annoyance of a red checkmark~~
- Remove use function var_dump
=> Minor fixes

src/Attachment.php, src/Parser.php
As it does not make sense to have anything protected in a final class.
This is a continuation of what was done in #292
=> Make protected functions private

composer.json, src/Attachment.php, src/Contracts/AttachmentInterface.php, src/Parser.php, tests/AttachmentTest.php, tests/stubs/AnotherAttachment.php
=> Loosly Coupled Attachment Class

src/Attachment.php, src/Contracts/AttachmentInterface.php, src/Contracts/ParserInterface.php, src/MimePart.php, src/Parser.php, tests/AttachmentTest.php, tests/ExceptionTest.php, tests/ParserTest.php, tests/stubs/AnotherAttachment.php
=> Refacto getAttachments

README.md
Add installation commands for a  php docker image (with alpine distribution)
=> Add installation commands for a  php docker image

src/ContentTransferDecoder.php, src/Contracts/ContentTransferEncodingManager.php, tests/AttachmentTest.php, tests/mails/uuencode.eml
Fix issue #330 
https://en.wikipedia.org/wiki/Uuencoding
=> Implement uuencode

src/Charset.php, src/Parser.php, tests/ParserTest.php, tests/mails/issue329
Fix issue https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/329
=> Encode to UTF8 for US-ASCII

tests/ParserTest.php
=> Get Raw Header Return Array

src/Parser.php
=> Fix issue 444

.github/workflows/main.yml, composer.json
PHP 8.4 deprecation warnings have already been fixed in https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/446
=> Test against PHP 8.4

src/Parser.php
=> Fix phpdoc for Parser::getInlineParts

src/Parser.php, tests/ExceptionTest.php
=> Fix Exception htmlEmbedded
